export const browserCoreExamples = [
  "theiaos browser status",
  "theiaos browser start",
  "theiaos browser stop",
  "theiaos browser tabs",
  "theiaos browser open https://example.com",
  "theiaos browser focus abcd1234",
  "theiaos browser close abcd1234",
  "theiaos browser screenshot",
  "theiaos browser screenshot --full-page",
  "theiaos browser screenshot --ref 12",
  "theiaos browser snapshot",
  "theiaos browser snapshot --format aria --limit 200",
  "theiaos browser snapshot --efficient",
  "theiaos browser snapshot --labels",
];

export const browserActionExamples = [
  "theiaos browser navigate https://example.com",
  "theiaos browser resize 1280 720",
  "theiaos browser click 12 --double",
  'theiaos browser type 23 "hello" --submit',
  "theiaos browser press Enter",
  "theiaos browser hover 44",
  "theiaos browser drag 10 11",
  "theiaos browser select 9 OptionA OptionB",
  "theiaos browser upload /tmp/theiaos/uploads/file.pdf",
  'theiaos browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "theiaos browser dialog --accept",
  'theiaos browser wait --text "Done"',
  "theiaos browser evaluate --fn '(el) => el.textContent' --ref 7",
  "theiaos browser console --level error",
  "theiaos browser pdf",
];
